### ISSUE TITLE
 minikube up and running on your machine machine.

### ISSUE THREAD

**Issue by akashpatel2699** [akashpatel2699/IT490-Project#21]
Have minikube installed and running on your local machine for future milestone.

**Comment by nourahedhli** [comment]
Got it

**Comment by nbaryah** [comment]
DONE

![image](https://user-images.githubusercontent.com/54951344/115320414-d56b4f00-a14f-11eb-9491-090c846e3686.png)

**Comment by akashpatel2699** [comment]
Great!
